---
pagetitle: "AMPC2020"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    includes:
      in_header: header.html    
---

<br><br>

## Abstract Submission

For AMPC 2020 we are proposing a mix of long and short talks. A long talk is allocated a total of 20 minutes (15 minutes for the talk, 5 minutes of questions), and a short talk is allocated 10 minutes (8 minutes for the talk, 2 minutes of questions).

The deadline for submissions and registration is **January 27th, 2020**. To submit your abstract, follow the link to the [submission portal](https://forms.gle/VzkCE29zU5NdovdK9).


<br><br>

## Conference Registration

Registration for the conference is now open. Student registration is \$120 and 
full registration is \$220. The conference dinner will be held at [BarZura](https://www.barzura.com.au/). The dinner cost is \$73 and there is 
a strict limit of 45 dinner tickets for sale. To register for the conference visit the [Eventbrite page](https://www.eventbrite.com.au/e/australian-mathematical-psychology-conference-2020-tickets-5404801908)

<br><br>

## Conference Schedule

A detailed schedule and program of abstracts will be posted closer to the event. The overall plan, however, is to run all-day schedules on Wednesday and Thursday and a half-day on Friday. The conference dinner will be on Thursday night.

<br><br>

## Venue and Accomodation

The venue for the conference will be the [Coogee Bay Hotel](https://coogeebayhotel.com.au/) opposite the lovely Coogee Beach. We will not be arranging conference deals for accomodation, but there are many accommodation options in and around Coogee. A few possibilities are listed below: 

- [Crowne Plaza Coogee](https://www.ihg.com/crowneplaza/hotels/us/en/sydney/sydcb/hoteldetail?cm_mmc=GoogleMaps-_-CP-_-AU-_-SYDCB)
- [Dive Hotel](https://www.divehotel.com.au/)
- [Adina Apartment Hotel, Coogee](https://www.adinahotels.com/en/apartments/coogee-sydney/?gclid=Cj0KCQjwuNbsBRC-ARIsAAzITuc36WI9_zJtKVAOP9fgUpE3DokuA0ED96KvDzsabyRWOn4mJ2n6boYaAhVwEALw_wcB&gclsrc=aw.ds)

<br><br>

## Code of Conduct

All attendees, speakers, sponsors and volunteers at our conference are required to agree with the following code of conduct. Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media.

If you have any concerns during your time at the conference, please contact one of the organisers. 

<!-- Alternatively you can make an anonymous submission through our online portal.  -->

<br><br>

## Organisers

The AMPC conference organisers are:

- Brett Hayes (b.hayes@unsw.edu.au)
- Ben Newell (ben.newell@unsw.edu.au)
- Chris Donkin (c.donkin@unsw.edu.au)
- Danielle Navarro (d.navarro@unsw.edu.au)
 
 
<br><br>

## Acknowledgment of Country

We would like to acknowledge the Gadigal and Bidjigal peoples who are the traditional custodians of the land on which the AMPC2020 meeting takes place.
